[package]
name = "arxiv-rs"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[lib]
name = "arxiv"

[dependencies]
async-std = { version = "1.6.0", features = ["attributes"] }
surf = "1.0.3"
anyhow = "1.0.32"
xml-rs = "0.8.3"
